name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Build and run test Node.js Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint Static Analysis
        run: npx eslint . -f json -o eslint_report.json  

      - name: ESLint Annotate
        uses: ataylorme/eslint-annotate-action@v3
        with:
          only-pr-files: false
        continue-on-error: true

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 
            ${{ secrets.DOCKERHUB_USERNAME }}/jest-test-deploy:latest
