name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Build and run test Node.js Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
